export const Watchs = [
  {
    id: 1,
    Name: "FOGG ",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/watch/r/a/t/-original-imagttd6m6ysskuz.jpeg?q=70",
    price: "275",
    Type: "Mens",
    Category: "fashion",
    Disc: "2046-BK Day and Date Analog Watch - For Men 2046-BK",
  },
  {
    id: 2,
    Name: "Fastrack ",
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/7/x/e/-original-imagnqcg8ptygbjv.jpeg?q=70",
    price: "250",
    Type: "women",
    Category: "fashion",
    Disc: "Warranty Period 2 Years , 5 ATM/50 m Water resistance. Leather Strap. Stainless steel back cover. High precision quartz analogue movement.",
  },
  {
    id: 3,
    Name: "LORENZ  ",
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/l/e/d/-original-imagrdzepg5evemf.jpeg?q=70",
    price: "515 ",
    Type: "Mens",
    Category: "fashion",
    Disc: "jwefd",
  },
  {
    id: 4,
    Name: "V2A ",
    img: "https://rukminim2.flixcart.com/image/832/832/kltryq80/watch/v/k/f/stylish-trendy-analog-digital-sports-casual-water-resistant-original-imagyvbwvjru9zzq.jpeg?q=70",
    price: "499",
    Type: "men",
    Category: "casual",
    Disc: "jwefd",
  },
  {
    id: 5,
    Name: "Fastrack  ",
    img:"https://rukminim2.flixcart.com/image/612/612/xif0q/watch/i/5/u/-original-imagpzjf8wbee3yg.jpeg?q=70",
    price: "989",
    Type: "men",
    Category: "casual",
    Disc: "jwefd",
  },
  {
    id: 6,
    Name: "Titan   ",
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/s/r/0/-original-imagnvwugzye4cmd.jpeg?q=70",
    price: "1899",
    Type: "men",
    Category: "casual",
    Disc: "jwefd",
  },
  {
    id: 7,
    Name: "TIMEX   ",
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/j/m/g/-original-imagsykvfqzvxqdv.jpeg?q=70",
    price: "689",
    Type: "men",
    Category: "casual",
    Disc: "jwefd",
  },
  {
    id: 8,
    Name: "Rolex  ",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/watch/m/a/i/-original-imagrcjkpwzzbttr.jpeg?q=70",
    price: "999",
    Type: "men",
    Category: "stylish",
    Disc: "jwefd",
  },
  {
    id: 9,
    Name: "LIMESTONE ",
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/r/z/t/-original-imagrdzf3mymwx7f.jpeg?q=70",
    price: "190",
    Type: "men",
    Category: "casual",
    Disc: "jwefd",
  },
  {
    id: 10,
    Name: "LORENZ  ",
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/l/e/d/-original-imagrdzepg5evemf.jpeg?q=70",
    price: "515 ",
    Type: "Mens",
    Category: "fashion",
    Disc: "jwefd",
  },
  {
    id: 11,
    Name: "V2A ",
    img: "https://rukminim2.flixcart.com/image/832/832/kltryq80/watch/v/k/f/stylish-trendy-analog-digital-sports-casual-water-resistant-original-imagyvbwvjru9zzq.jpeg?q=70",
    price: "499",
    Type: "men",
    Category: "casual",
    Disc: "jwefd",
  },
  {
    id: 12,
    Name: "Fastrack  ",
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/w/s/d/-original-imagnqcjgxcxmfjb.jpeg?q=70",
    price: "989",
    Type: "men",
    Category: "casual",
    Disc: "jwefd",
  },
  {
    id: 13,
    Name: "Titan   ",
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/s/r/0/-original-imagnvwugzye4cmd.jpeg?q=70",
    price: "1899",
    Type: "men",
    Category: "casual",
    Disc: "jwefd",
  },
  {
    id: 14,
    Name: "TIMEX   ",
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/j/m/g/-original-imagsykvfqzvxqdv.jpeg?q=70",
    price: "689",
    Type: "men",
    Category: "casual",
    Disc: "jwefd",
  },
  {
    id: 15,
    Name: "Rolex  ",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/watch/m/a/i/-original-imagrcjkpwzzbttr.jpeg?q=70",    price: "999",
    Type: "men",
    Category: "stylish",
    Disc: "jwefd",
  },
  {
    id: 16,
    Name: "LIMESTONE ",
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/r/z/t/-original-imagrdzf3mymwx7f.jpeg?q=70",
    price: "190",
    Type: "men",
    Category: "casual",
    Disc: "jwefd",
  },
  {
    id: 17,
    Name: "FOGG ",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/watch/r/a/t/-original-imagttd6m6ysskuz.jpeg?q=70",
    price: "275",
    Type: "Mens",
    Category: "fashion",
    Disc: "2046-BK Day and Date Analog Watch - For Men 2046-BK",
  },
  {
    id: 18,
    Name: "Fastrack ",
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/7/x/e/-original-imagnqcg8ptygbjv.jpeg?q=70",
    price: "250",
    Type: "women",
    Category: "fashion",
    Disc: "jwefd",
  },
  {
    id: 19,
    Name: "Titan   ",
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/s/r/0/-original-imagnvwugzye4cmd.jpeg?q=70",
    price: "1899",
    Type: "men",
    Category: "casual",
    Disc: "jwefd",
  },
  {
    id: 20,
    Name: "TIMEX   ",
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/j/m/g/-original-imagsykvfqzvxqdv.jpeg?q=70",
    price: "689",
    Type: "men",
    Category: "casual",
    Disc: "jwefd",
  },
  {
    id: 21,
    Name: "Rolex  ",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/watch/m/a/i/-original-imagrcjkpwzzbttr.jpeg?q=70",    price: "999",
    Type: "men",
    Category: "stylish",
    Disc: "jwefd",
  },
  {
    id: 22,
    Name: "LIMESTONE ",
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/r/z/t/-original-imagrdzf3mymwx7f.jpeg?q=70",
    price: "190",
    Type: "men",
    Category: "casual",
    Disc: "jwefd",
  },
  {
    id: 23,
    Name: "LORENZ  ",
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/l/e/d/-original-imagrdzepg5evemf.jpeg?q=70",
    price: "515 ",
    Type: "Mens",
    Category: "fashion",
    Disc: "jwefd",
  },
  {
    id: 24,
    Name: "V2A ",
    img: "https://rukminim2.flixcart.com/image/832/832/kltryq80/watch/v/k/f/stylish-trendy-analog-digital-sports-casual-water-resistant-original-imagyvbwvjru9zzq.jpeg?q=70",
    price: "499",
    Type: "men",
    Category: "casual",
    Disc: "jwefd",
  },
  {
    id: 25,
    Name: "Fastrack  ",
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/w/s/d/-original-imagnqcjgxcxmfjb.jpeg?q=70",
    price: "989",
    Type: "men",
    Category: "casual",
    Disc: "jwefd",
  },
  {
    id: 26,
    Name: "Titan   ",
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/s/r/0/-original-imagnvwugzye4cmd.jpeg?q=70",
    price: "1899",
    Type: "men",
    Category: "casual",
    Disc: "jwefd",
  },
  {
    id: 27,
    Name: "TIMEX   ",
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/j/m/g/-original-imagsykvfqzvxqdv.jpeg?q=70",
    price: "689",
    Type: "men",
    Category: "casual",
    Disc: "jwefd",
  },
  {
    id: 28,
    Name: "Rolex  ",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/watch/m/a/i/-original-imagrcjkpwzzbttr.jpeg?q=70",    price: "999",
    Type: "men",
    Category: "stylish",
    Disc: "jwefd",
  },
  {
    id: 29,
    Name: "LIMESTONE ",
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/watch/r/z/t/-original-imagrdzf3mymwx7f.jpeg?q=70",
    price: "190",
    Type: "men",
    Category: "casual",
    Disc: "jwefd",
  },
  {
    id: 30,
    Name: "FOGG ",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/watch/r/a/t/-original-imagttd6m6ysskuz.jpeg?q=70",
    price: "275",
    Type: "Mens",
    Category: "fashion",
    Disc: "2046-BK Day and Date Analog Watch - For Men 2046-BK",
  },
];
